-- CLI: writes an icosphere .obj asset.
-- Usage: cd game && lua ../tools/gen_icosphere.lua [subdivisions] [output_path]

local PHI = (1 + math.sqrt(5)) / 2

local function normalize(v)
    local len = math.sqrt(v[1] * v[1] + v[2] * v[2] + v[3] * v[3])
    return { v[1] / len, v[2] / len, v[3] / len }
end

local function base_icosahedron()
    local vertices = {
        { -1, PHI, 0 }, { 1, PHI, 0 }, { -1, -PHI, 0 }, { 1, -PHI, 0 },
        { 0, -1, PHI }, { 0, 1, PHI }, { 0, -1, -PHI }, { 0, 1, -PHI },
        { PHI, 0, -1 }, { PHI, 0, 1 }, { -PHI, 0, -1 }, { -PHI, 0, 1 },
    }
    for i, v in ipairs(vertices) do
        vertices[i] = normalize(v)
    end
    local faces = {
        { 1, 12, 6 }, { 1, 6, 2 }, { 1, 2, 8 }, { 1, 8, 11 }, { 1, 11, 12 },
        { 2, 6, 10 }, { 6, 12, 5 }, { 12, 11, 3 }, { 11, 8, 7 }, { 8, 2, 9 },
        { 4, 10, 5 }, { 4, 5, 3 }, { 4, 3, 7 }, { 4, 7, 9 }, { 4, 9, 10 },
        { 5, 10, 6 }, { 3, 5, 12 }, { 7, 3, 11 }, { 9, 7, 8 }, { 10, 9, 2 },
    }
    return vertices, faces
end

-- Every edge midpoint is shared by the two triangles it splits, so we cache
-- it by an order-independent key and reuse the same vertex on both sides —
-- without this, adjacent faces would each grow their own copy and the mesh
-- would tear apart at every subdivided edge.
local function midpoint_index(vertices, cache, i1, i2)
    local key = i1 < i2 and (i1 .. ":" .. i2) or (i2 .. ":" .. i1)
    local index = cache[key]
    if index then
        return index
    end
    local a, b = vertices[i1], vertices[i2]
    vertices[#vertices + 1] = normalize({ (a[1] + b[1]) / 2, (a[2] + b[2]) / 2, (a[3] + b[3]) / 2 })
    index = #vertices
    cache[key] = index
    return index
end

local function subdivide(vertices, faces)
    local cache = {}
    local new_faces = {}
    for _, face in ipairs(faces) do
        local a, b, c = face[1], face[2], face[3]
        local ab = midpoint_index(vertices, cache, a, b)
        local bc = midpoint_index(vertices, cache, b, c)
        local ca = midpoint_index(vertices, cache, c, a)
        new_faces[#new_faces + 1] = { a, ab, ca }
        new_faces[#new_faces + 1] = { b, bc, ab }
        new_faces[#new_faces + 1] = { c, ca, bc }
        new_faces[#new_faces + 1] = { ab, bc, ca }
    end
    return new_faces
end

local subdivisions = tonumber(arg[1]) or 1
local output_path = arg[2] or "assets/sphere.obj"

local vertices, faces = base_icosahedron()
for _ = 1, subdivisions do
    faces = subdivide(vertices, faces)
end

local lines = {
    string.format("# generated by tools/gen_icosphere.lua (subdivisions=%d)", subdivisions),
}
for _, v in ipairs(vertices) do
    lines[#lines + 1] = string.format("v %.7g %.7g %.7g", v[1], v[2], v[3])
end

lines[#lines + 1] = ""
lines[#lines + 1] = "# UV per face corner: each face gets its own independent vt block, never"
lines[#lines + 1] = "# shared with another face -- an undistorted triangle mapping (first corner"
lines[#lines + 1] = "# to top-center, the other two to bottom-left/right), the same convention"
lines[#lines + 1] = "# used by assets/prism.obj and assets/pyramid.obj."
for _ = 1, #faces do
    lines[#lines + 1] = "vt 0.5 1.0"
    lines[#lines + 1] = "vt 0.0 0.0"
    lines[#lines + 1] = "vt 1.0 0.0"
end
lines[#lines + 1] = ""

local vt = 0
for _, f in ipairs(faces) do
    lines[#lines + 1] = string.format("f %d/%d %d/%d %d/%d", f[1], vt + 1, f[2], vt + 2, f[3], vt + 3)
    vt = vt + 3
end

local file = assert(io.open(output_path, "w"))
file:write(table.concat(lines, "\n"), "\n")
file:close()

print(string.format("wrote %d vertices, %d faces to %s", #vertices, #faces, output_path))
